#!/bin/bash

# ensure that multiple, simultaneous daemons are not started by this user ID
# assume that pwd has this file

EXECUTABLE_SCRIPT=./helper.py

# MY_UID=`id -u`
# KEY=vm7
# THE_PID="`/usr/bin/pgrep ${KEY}\$ -u ${MY_UID}`"

# if [ "" != "${THE_PID}" ] ; then
#   echo "${KEY} is already running, won't start a new one, PID=${THE_PID}"
#   exit 1
# fi

# start the daemon
source /APSshare/anaconda3/x86_64/bin/activate
# needs stdlogpj package
conda activate bluesky
python ${EXECUTABLE_SCRIPT}
